# Randomizes per-build settings:
#   1. Random module name  -> Android.mk MODULE_NAME (defeats process-name/filename blacklists)
#   2. Random opt level    -> Android.mk BUILD_OPT_LEVEL
#   3. Random build entropy -> rewrites jni/src/build_entropy.h (defeats binary-hash blacklists)
# Invoked by 1.bat before ndk-build. ASCII-only output on purpose: this file is
# consumed by cmd.exe / included by a C++ header, and non-ASCII text has previously
# caused mojibake that silently broke both.
$ErrorActionPreference = "Stop"

$jniRoot = Split-Path -Parent $PSScriptRoot   # .../jni
$repoRoot = Split-Path -Parent $jniRoot       # project root

$modName = -join ((97..122) | Get-Random -Count 8 | ForEach-Object { [char]$_ })
$optLevel = @("-O1", "-O2", "-O3") | Get-Random

$bytes = 1..64 | ForEach-Object { Get-Random -Minimum 0 -Maximum 256 }
$hexList = ($bytes | ForEach-Object { "0x{0:x2}" -f $_ }) -join ", "
$tag = -join ((97..122) + (48..57) | Get-Random -Count 16 | ForEach-Object { [char]$_ })

$headerLines = @(
    "#pragma once",
    "#include <cstdint>",
    "",
    "// Auto-generated by gen_build_vars.ps1 before every build. Random on purpose:",
    "// only exists to change the compiled artifact's bytes/hash each time.",
    "static const unsigned char g_build_entropy[64] = { $hexList };",
    "static const char g_build_tag[] = `"$tag`";",
    ""
)
$headerPath = Join-Path $jniRoot "src\build_entropy.h"
Set-Content -Path $headerPath -Value $headerLines -Encoding ascii

$varsLines = @(
    "set MODNAME=$modName",
    "set OPTLVL=$optLevel"
)
$varsPath = Join-Path $repoRoot "build_vars.bat"
Set-Content -Path $varsPath -Value $varsLines -Encoding ascii

Write-Host "[*] module=$modName.sh opt=$optLevel tag=$tag"
